logging.level.org.springframework.web=DEBUG
server.port=8100

# MariaDB Configuration
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/sepa26_db}
spring.datasource.username=${DB_USER:sepa_user}
spring.datasource.password=${DB_PASSWORD:sepa_password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 (Only for local dev console if needed)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Formatage & indentation XML / JSON (lisibilité des flux)
spring.jackson.serialization.indent-output=true

# Métadonnées de l'application (Page d'accueil)
app.name=Projet SEPA26
app.version=0.0.1-SNAPSHOT
app.developer=Florian Pépin
app.university-logo=https://www.choisirlanormandie.fr/app/uploads/2024/08/logo-universite-de-rouen.png